services:
  mongodb:
    image: mongo:latest
    container_name: zrun-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  backend:
    build: 
      context: .
      dockerfile: backend.Dockerfile
    container_name: zrun-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:password@mongodb:27017/zrun?authSource=admin
      - SPRING_DATA_MONGODB_DATABASE=zrun
      - SPRING_PROFILES_ACTIVE=dev

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: zrun-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080

volumes:
  mongodb_data: