services:
  mongodb:
    image: mongo:latest
    container_name: zrun-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: zrun-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:password@mongodb:27017/zrun?authSource=admin
      - SPRING_DATA_MONGODB_DATABASE=zrun
      - SPRING_PROFILES_ACTIVE=dev


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: zrun-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    working_dir: /app

volumes:
  mongodb_data: