name: Documentation Update
description: Suggest improvements or report issues in documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve ZRun's documentation!
  - type: dropdown
    id: type
    attributes:
      label: Type of documentation change
      options:
        - New documentation needed
        - Existing documentation needs update
        - Documentation is incorrect
        - Documentation needs clarification
        - Other
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation you're referring to? (URL, file path, etc.)
      placeholder: README.md, /docs/setup.md, etc.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be changed/added/fixed in the documentation?
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Changes
      description: If you have specific wording suggestions, please provide them here.