spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}?authSource=admin
  application:
    name: zrun
  devtools:
    restart:
      enabled: true

zrun:
  admin:
    email: ${ADMIN_EMAIL:admin@zrun.com}
    password: ${ADMIN_PASSWORD:adminpass}
    name: ${ADMIN_NAME:Admin User}
  security:
    jwt:
      secret: ${JWT_SECRET:v3ryS3cr3tK3yTh@tSh0uldB3L0ngEnoughForHS512Alg0r1thm}
      expiration: ${JWT_EXPIRATION:86400000} 

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

# Actuator Configuration
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      enabled: true
  info:
    enabled: true

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: DEBUG
    com.zrun: DEBUG
    org.springframework.web: INFO