spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}?authSource=admin
  application:
    name: zrun

zrun:
  admin:
    email: ${ADMIN_EMAIL:admin@zrun.com}
    password: ${ADMIN_PASSWORD:adminpass}
    name: ${ADMIN_NAME:Admin User}
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:86400000} 

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: DEBUG